# Generated by Django 4.2 on 2023-05-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('owner', models.CharField(max_length=200)),
                ('availability', models.BooleanField(default=True)),
                ('availability_change_date', models.DateTimeField(verbose_name='date availability changed')),
                ('change_date', models.DateTimeField(verbose_name='date changed')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('owner', models.CharField(max_length=200)),
                ('availability', models.BooleanField(default=True)),
                ('availability_change_date', models.DateTimeField(verbose_name='date availability changed')),
                ('change_date', models.DateTimeField(verbose_name='date changed')),
            ],
        ),
    ]
